# Generated by Django 3.2.16 on 2022-11-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_auth_mafiasi", "0004_add_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tokens",
                        serialize=False,
                        to="django_auth_mafiasi.mafiasiauthmodeluser",
                    ),
                ),
                ("access_token", models.CharField(max_length=256)),
                ("access_expiry", models.DateTimeField()),
                ("refresh_token", models.CharField(max_length=256)),
                ("refresh_expiry", models.DateTimeField()),
            ],
        ),
    ]
